package com.rackspace.cloud.api.entity;

// Generated Sep 21, 2014 11:03:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Latestwardeploy generated by hbm2java
 */
@Entity
@Table(name = "latestwardeploy", catalog = "docs")
public class Latestwardeploy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 406821597571531609L;
	private Integer id;
	private String warname;
	private String groupid;
	private String artifactid;
	private String nexuslatestincludewawrsjar;
	private Date latest;
	private String timezone;
	private String serverenv;

	public Latestwardeploy() {
	}

	public Latestwardeploy(String warname) {
		this.warname = warname;
	}

	public Latestwardeploy(String warname, String groupid, String artifactid,
			String nexuslatestincludewawrsjar, Date latest, String timezone,
			String serverenv) {
		this.warname = warname;
		this.groupid = groupid;
		this.artifactid = artifactid;
		this.nexuslatestincludewawrsjar = nexuslatestincludewawrsjar;
		this.latest = latest;
		this.timezone = timezone;
		this.serverenv = serverenv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "warname", nullable = false, length = 100)
	public String getWarname() {
		return this.warname;
	}

	public void setWarname(String warname) {
		this.warname = warname;
	}

	@Column(name = "groupid", length = 150)
	public String getGroupid() {
		return this.groupid;
	}

	public void setGroupid(String groupid) {
		this.groupid = groupid;
	}

	@Column(name = "artifactid", length = 150)
	public String getArtifactid() {
		return this.artifactid;
	}

	public void setArtifactid(String artifactid) {
		this.artifactid = artifactid;
	}

	@Column(name = "nexuslatestincludewawrsjar", length = 300)
	public String getNexuslatestincludewawrsjar() {
		return this.nexuslatestincludewawrsjar;
	}

	public void setNexuslatestincludewawrsjar(String nexuslatestincludewawrsjar) {
		this.nexuslatestincludewawrsjar = nexuslatestincludewawrsjar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "latest", length = 19)
	public Date getLatest() {
		return this.latest;
	}

	public void setLatest(Date latest) {
		this.latest = latest;
	}

	@Column(name = "timezone", length = 30)
	public String getTimezone() {
		return this.timezone;
	}

	public void setTimezone(String timezone) {
		this.timezone = timezone;
	}

	@Column(name = "serverenv", length = 10)
	public String getServerenv() {
		return this.serverenv;
	}

	public void setServerenv(String serverenv) {
		this.serverenv = serverenv;
	}

}
